### ISSUE TITLE
Error: Could not find report file

### ISSUE THREAD

**Issue by pamelafracalossi** [maciejmaciejewski/azure-pipelines-protractor#16]
YAML setup:

![image](https://user-images.githubusercontent.com/39679905/89663735-6218fa00-d8ac-11ea-92c1-fb55e6709700.png)

Protractor conf:

![image](https://user-images.githubusercontent.com/39679905/89663869-a2787800-d8ac-11ea-86b9-a8acc81f388e.png)

Azure Result:

![image](https://user-images.githubusercontent.com/39679905/89663968-c936ae80-d8ac-11ea-8dc6-f2dea9fdaa54.png)

What am I doing wrong?

**Comment by maciejmaciejewski** [comment]
Hey 👋 
There is most probably mismatch between directories.
I see that in script your working directory is `$(Build. SourcesDirectory)/automacao` but in the report publish task you are using `$(System.DefaultWorkingDirectory)/protractor`.

According to [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) Both variables should resolve to the same value, for example `c:\agent_work\1\s` 

Plase make sure that the path are correct, to validate please run your build with `system.debug` variable set to true.

**Comment by pamelafracalossi** [comment]
@maciejmaciejewski  thank you very much. I changed my working directory and the problem was solved. I will leave it below a final configuration in case someone needs it in the future.

![image](https://user-images.githubusercontent.com/39679905/89816484-0acd9080-db1d-11ea-8d47-ee4a1c0b9f6f.png)
