### ISSUE TITLE
Protractor Report not Showing Images in AZURE DEVOPS

### ISSUE THREAD

**Issue by ybc9959** [maciejmaciejewski/azure-pipelines-protractor#6]
**Protractor Beautiful Reporter** is working fine and I was able to see all the **screenshots** and index.html file in temp folder.
 When I open the Index.html folder from my local, I was able to see the Report with failed screenshots and all the Logs what I expected.
Now I configured same thing in Azure Devops , Everything is Displaying well **except the screenshots.**
When **I click on the image it was blank**, checked locally and html report works fine. Attaching some  screenshots.
![1](https://user-images.githubusercontent.com/60444579/73386314-4517c480-4294-11ea-859f-8a1820739668.PNG)
![2](https://user-images.githubusercontent.com/60444579/73386318-45b05b00-4294-11ea-84b5-f245394f8fb7.PNG)
![3](https://user-images.githubusercontent.com/60444579/73386319-4648f180-4294-11ea-9d22-642acda0759c.PNG)

**Comment by ybc9959** [comment]
Attaching Code below.
onPrepare: function() {
        // Add a screenshot reporter and store screenshots to `/tmp/screenshots`:
        jasmine.getEnv().addReporter(new HtmlReporter({
            baseDirectory: 'tmp/screenshots',
            docName: 'index.html',
            docTitle: 'my reporter',
            takeScreenShotsOnlyForFailedSpecs: true,
            excludeSkippedSpecs: true,
            preserveDirectory: false,
            gatherBrowserLogs: false,
            sortFunction: function sortFunction(a, b) {
                if (a.cachedBase === undefined) {
                    var aTemp = a.description.split('|').reverse();
                    a.cachedBase = aTemp.slice(0).slice(0, -1);
                    a.cachedName = aTemp.slice(0).join('');
                };
                if (b.cachedBase === undefined) {
                    var bTemp = b.description.split('|').reverse();
                    b.cachedBase = bTemp.slice(0).slice(0, -1);
                    b.cachedName = bTemp.slice(0).join('');
                };

                var firstBase = a.cachedBase;
                var secondBase = b.cachedBase;

                for (var i = 0; i < firstBase.length || i < secondBase.length; i++) {

                    if (firstBase[i] === undefined) { return -1; }
                    if (secondBase[i] === undefined) { return 1; }
                    if (firstBase[i].localeCompare(secondBase[i]) === 0) { continue; }
                    return firstBase[i].localeCompare(secondBase[i]);
                }

                var firstTimestamp = a.timestamp;
                var secondTimestamp = b.timestamp;

                if (firstTimestamp < secondTimestamp) return -1;
                else return 1;
            },
            clientDefaults: {
                searchSettings: {
                    allselected: false,
                    passed: false,
                    failed: true,
                    pending: true,
                    withLog: true
                },
                columnSettings: {
                    displayTime: true,
                    displayBrowser: true,
                    displaySessionId: false,
                    displayOS: true,
                    inlineScreenshots: false
                },
                showTotalDurationIn: "header",
                totalDurationFormat: "hms",

            }
        }).getJasmine2Reporter());
    },
![1](https://user-images.githubusercontent.com/60444579/73386839-25cd6700-4295-11ea-824b-24edc948061f.PNG)

**Comment by maciejmaciejewski** [comment]
@ybc9959 
Thank you for reporting this issue

Could you please specify which version of the reporter you are using.
Also If you could run your build pipeline with variable `system.debug=true` to confirm that screenshot have been uploaded. You should see 

Attached copy of the task execution
[log.txt](https://github.com/maciejmaciejewski/azure-pipelines-protractor/files/4132715/log.txt)

**Comment by maciejmaciejewski** [comment]
Issue is most probably caused by path separators when pipeline runs on Windows based agents.

**Comment by ybc9959** [comment]
Please find the attached Logs & Version 
![1 Image not loading](https://user-images.githubusercontent.com/60444579/73477266-86be7300-4359-11ea-9c0a-986d3f5ce2d7.PNG)
![Reporter version with updated one](https://user-images.githubusercontent.com/60444579/73477273-89b96380-4359-11ea-86e7-2911a7324e61.PNG)
![version](https://user-images.githubusercontent.com/60444579/73477280-8b832700-4359-11ea-8835-b39610acf1b5.PNG)
![packagejson](https://user-images.githubusercontent.com/60444579/73477282-8cb45400-4359-11ea-9770-64e2ef9f7612.PNG)
![Log](https://user-images.githubusercontent.com/60444579/73477285-8e7e1780-4359-11ea-9e03-1a3adc866e2e.PNG)

**Comment by maciejmaciejewski** [comment]
@ybc9959 
Bear in mind that extension looks for **combined.json** file in root directory of your report and then it searches for screenshots in **screenshots** subdirectory.

Please try adding following line to your reporter configuration

      screenshotsSubfolder: 'screenshots',

**Comment by ybc9959** [comment]
Yeah I see that the task is looking for Combined.json file. 

- Changed the Screenshot to Sub folder.
I see the screenshots are pointed in combine.json file(attached for refernce). Html file Displays Screenshots well in Local, but still I see Images are not Loading in Azure
![1](https://user-images.githubusercontent.com/60444579/73484656-5251b380-4367-11ea-925d-0c04c616f605.PNG)
![2](https://user-images.githubusercontent.com/60444579/73484657-5382e080-4367-11ea-8f63-f73745275534.PNG)
